package com.dshanywhere.core.protocol

/**
 * Generated from ios/DSHAnywhere/Localizable.xcstrings (read-only source).
 * English literals act as keys; missing keys fall through to the key itself.
 */
internal val ZH_TRANSLATIONS: Map<String, String> = mapOf(
    "%@ is unreachable" to "%@ 无法连接",
    "About" to "关于",
    "Active session" to "活跃会话",
    "Allow once" to "允许一次",
    "Archive" to "归档",
    "Archive session" to "归档会话",
    "Archived" to "已归档",
    "Ask" to "询问",
    "Ask every time" to "每次都询问",
    "Attach file" to "添加文件",
    "Attach photo" to "添加图片",
    "Attachments" to "附件",
    "Back" to "返回",
    "Bring a machine online to start a session." to "请先让设备上线，再开始会话。",
    "By workspace" to "按工作区",
    "Camera unavailable" to "相机不可用",
    "Cancel" to "取消",
    "Changes the sandbox and approval policy for this session" to "更改此会话的沙箱与审批策略",
    "Close" to "关闭",
    "Close settings" to "关闭设置",
    "Code copied" to "代码已复制",
    "Collapse composer controls" to "折叠编辑框操作",
    "Collapse project" to "收起项目",
    "Command completed" to "命令已完成",
    "Command not found" to "找不到该命令",
    "Commands" to "命令",
    "Connect to DeepSeek Harness" to "连接 DeepSeek Harness",
    "Connected" to "已连接",
    "Connecting…" to "正在连接…",
    "Connection" to "连接",
    "Connection failed" to "连接失败",
    "Context %lld percent used" to "上下文已用 %lld 个百分点",
    "Copied" to "已复制",
    "Copy" to "复制",
    "Copy code" to "复制代码",
    "Could not read that photo. If it is stored in iCloud, open it in Photos once so it downloads, then try again." to "无法读取这张照片。如果它存在 iCloud 中，请先在「照片」里打开一次让它下载，然后重试。",
    "Create" to "创建",
    "Create your first Harness session." to "创建你的第一个 Harness 会话。",
    "Created just now" to "刚刚创建",
    "DSH Anywhere" to "DSH Anywhere",
    "Delete" to "删除",
    "Delete project" to "删除项目",
    "Delete this message?" to "删除这条消息？",
    "Devices" to "设备",
    "Devices paired to this Mac, as reported by the relay. Revoking one signs that device out immediately." to "已与此 Mac 配对的设备（由 relay 提供）。撤销会立即使该设备退出登录。",
    "Disconnect" to "断开连接",
    "Disconnect this iPhone" to "断开此 iPhone",
    "Disconnect this iPhone?" to "要断开此 iPhone 吗？",
    "Disconnected" to "已断开",
    "Disconnecting removes the device token from this iPhone's keychain. The Mac keeps running." to "断开只会从本机钥匙串移除设备令牌，Mac 上的服务不受影响。",
    "Done" to "完成",
    "English" to "English",
    "Enter message…" to "输入消息…",
    "Enter the machine ID shown by DSH Anywhere Connector." to "请输入 DSH Anywhere Connector 显示的机器 ID。",
    "Enter the pairing code or secret shown by DSH Anywhere Connector." to "请输入 DSH Anywhere Connector 显示的配对码或密钥。",
    "Expand project" to "展开项目",
    "File" to "文件",
    "Filter and sort sessions" to "筛选与排序会话",
    "Filter sessions" to "筛选会话",
    "Flat list" to "平铺列表",
    "Follow System" to "跟随系统",
    "Follow System uses your device language. The choice applies immediately." to "「跟随系统」使用设备语言。选择会立即生效。",
    "Full access" to "完全访问",
    "Group by project" to "按项目分组",
    "Group by workspace" to "按工作区分组",
    "Harness can modify files inside the selected workspace." to "Harness 可以修改所选工作区内的文件。",
    "Harness can read and modify files outside the workspace." to "Harness 可以读取并修改工作区之外的文件。",
    "Hide archived" to "隐藏已归档",
    "Hide reasoning" to "收起思考过程",
    "Jump to latest output" to "回到最新输出",
    "Language" to "语言",
    "Machine" to "机器",
    "Machine ID" to "机器 ID",
    "Machines" to "机器",
    "Mode" to "模式",
    "Model" to "模型",
    "More actions" to "更多操作",
    "My Mac" to "我的 Mac",
    "Never ask" to "从不询问",
    "New session" to "新建会话",
    "New session in" to "在工作区中新建会话",
    "New session in %@" to "在 %@ 中新建会话",
    "No approvals" to "无需审批",
    "No devices reported." to "暂无设备。",
    "No messages yet" to "暂无消息",
    "No model catalog" to "没有模型目录",
    "No paired Macs yet." to "还没有配对的 Mac。",
    "No sessions" to "没有会话",
    "No sessions yet" to "暂无会话",
    "No workspace" to "不使用工作区",
    "No workspace is available yet" to "暂无可用工作区",
    "OK" to "好",
    "Offline" to "离线",
    "Online" to "在线",
    "Or enter manually" to "或手动输入",
    "Or enter the details manually" to "或手动输入机器信息",
    "Other answer" to "其他答案",
    "Pair with Mac" to "与 Mac 配对",
    "Pairing another Mac adds it here instead of replacing the current one. Tap to switch, swipe to remove." to "配对第二台 Mac 会添加到这里，而不是替换当前设备。点按切换，左滑移除。",
    "Pairing code or secret" to "配对码或密钥",
    "Permission" to "权限",
    "Permission mode" to "权限模式",
    "Permission required" to "需要权限",
    "Permission: %@" to "权限：%@",
    "Photo" to "图片",
    "Plan, ask, build…" to "规划、提问、构建…",
    "Project options" to "项目选项",
    "Read only" to "只读",
    "Reasoning behind %lld answers in this turn" to "本轮 %lld 条回答的思考过程",
    "Reasoning behind this answer" to "这条回答的思考过程",
    "Reasoning effort" to "思考深度",
    "Reconnect to load available models." to "重新连接以加载可用模型。",
    "Reconnecting (%lld)…" to "正在重新连接（%lld）…",
    "Refresh" to "刷新",
    "Refresh models" to "刷新模型",
    "Refresh project" to "刷新项目",
    "Refresh session info" to "刷新会话信息",
    "Reject" to "拒绝",
    "Relay" to "Relay",
    "Remove" to "移除",
    "Remove attachment" to "移除附件",
    "Rename project" to "重命名项目",
    "Revoke" to "撤销",
    "Run DSH Anywhere Connector on your Mac, then scan the pairing code it prints, or enter the machine details by hand." to "在 Mac 上运行 DSH Anywhere Connector，然后扫描它输出的配对码，或手动输入机器信息。",
    "Running" to "运行中",
    "Scan pairing code" to "扫描配对码",
    "Scanning needs a physical iPhone with an available camera. Enter the machine details by hand instead." to "扫描需要一台带可用摄像头的真机 iPhone。请改为手动输入机器信息。",
    "Select model" to "选择模型",
    "Send" to "发送",
    "Send a message, / command, @ file or conversation" to "发送消息，/ 命令，@ 文件或会话",
    "Send a prompt to your local DeepSeek Harness." to "向本机的 DeepSeek Harness 发送提示。",
    "Send answer" to "发送回答",
    "Send message" to "发送消息",
    "Sending" to "发送中",
    "Session icon" to "会话图标",
    "Session settings" to "会话设置",
    "Sessions" to "会话",
    "Settings" to "设置",
    "Show archived" to "显示已归档",
    "Show reasoning" to "查看思考过程",
    "Show session usage" to "显示会话用量",
    "Show turn usage beside Thinking" to "在“思考”旁显示本轮用量",
    "Something went wrong" to "出错了",
    "Start New Session" to "新建会话",
    "Start a conversation" to "开始对话",
    "Start one on a connected machine." to "在已连接的设备上开始一个会话。",
    "Status" to "状态",
    "Stop turn" to "停止本轮",
    "That is not a DSH Anywhere pairing code." to "这不是 DSH Anywhere 的配对码。",
    "This iPhone" to "此 iPhone",
    "This removes the message from this iPhone only. The original Harness history on your Mac is unchanged." to "只会从这台 iPhone 的会话视图中移除；Mac 上的 Harness 原始历史不会改变。",
    "Tool %@, %@" to "工具 %@，%@",
    "Troubleshoot" to "排查连接",
    "Type your answer" to "输入你的答案",
    "Unarchive" to "取消归档",
    "Unrecognised code %@" to "无法识别的码 %@",
    "Untitled session" to "未命名会话",
    "Version" to "版本",
    "Workspace" to "工作区",
    "Workspace changes" to "允许改动工作区",
    "Workspace menu" to "工作区菜单",
    "Workspace write" to "工作区可写",
    "You will need the Mac's machine ID and pairing secret to pair again." to "重新配对需要该 Mac 的机器 ID 与配对密钥。",
    "Your API keys stay on your Mac." to "你的 API key 只保存在 Mac 上。",
    "简体中文" to "简体中文",
)
